"""add api_key to users

Revision ID: 1b417b20971e
Revises: 
Create Date: 2026-04-16 11:00:23.239645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b417b20971e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'orders', 'users', ['owner_id'], ['user_id'])
    op.add_column('users', sa.Column('api_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['api_key'])
    op.create_foreign_key(None, 'vouchers', 'users', ['owner_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vouchers', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'api_key')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    # ### end Alembic commands ###
